name: Generate sdPendle Locker Monthly rewards repartition

on:
  workflow_dispatch:
  push:
    paths:
      - "data/swap-result.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"

      - name: Install node dependencies
        run: yarn install

      - name: Run sdPendle script
        run: |
          OUTPUT=$(yarn hardhat run scripts/sdPendle.ts)
          echo "::set-output name=output::$OUTPUT"
        shell: bash

      - name: Commit and push changes to bribes repo
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Stake DAO Automation"
          git add .
          git commit -m "Generating sdPendle Locker Monthly rewards repartition"
          git push origin main
        shell: bash
        if: ${{ success() }}
