name: Sync Fork with Parent Repository

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch changes from the parent repository
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main